version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.deine-domain.de`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./app.db

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`deine-domain.de`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

networks:
  web:
    external: true  # Das gleiche Netzwerk, in dem Traefik läuft
